baseurl      = "https://abandonedcrowley.github.io/AbandonedCrowley/"
title        = "作家之国"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

defaultContentLanguage = "zh"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Author's Country"

  disableReadOtherPosts = false

  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "作家之国"
  keywords = "homepage, blog, tech"
  images = [""]

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.zh]
    languageName = "中文" 
    weight = 1  
    title = "作家之国"
    
    [languages.zh.params]
      subtitle = "绕树三匝 何枝可依"
      readOtherPosts = "更多"

      [languages.zh.params.logo]
        logoText = "作家之国"
        logoHomeLink = "/"

    [[languages.zh.menu.main]]
      identifier = "blog"
      name       = "博客"
      url        = "/posts"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Author's Country"
    
    [languages.en.params]
      subtitle = "Author's Country"
      readOtherPosts = "Find More"

      # 英文版 Logo
      [languages.en.params.logo]
        logoText = "AC" 
        logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  # and submenus
  [[menu.main]]
    identifier  = "parent"
    name        = "Parent"
    url         = "/parent"
    hasChildren = true

  [[menu.main]]
    identifier  = "child"
    name        = "Child"
    url         = "/parent/child"
    parent      = "parent"